/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examples;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MCREMOTE
 */
public class MathGame extends javax.swing.JFrame {

    /**
     * Creates new form MathGame
     */
    public MathGame() {
        initComponents();
        init();
    }

    private void init() {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3_ammount_correct = new javax.swing.JLabel();
        jLabel4_ammount_wrong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4_total = new javax.swing.JLabel();
        jLabel4_count_down = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("STARTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Här kommer uppgiften");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("TESTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Rätt: ");

        jLabel2.setText("Fel:");

        jLabel3_ammount_correct.setText("....");

        jLabel4_ammount_wrong.setText("......");

        jLabel3.setText("Total:");

        jLabel4_total.setText(".....");

        jLabel4_count_down.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_count_down.setText(".....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3_ammount_correct)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4_ammount_wrong)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4_total))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(jTextField1)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4_count_down, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3_ammount_correct)
                    .addComponent(jLabel4_ammount_wrong)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4_count_down, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
//    int LOW = 9;
//    int HIGH = 50;
    //
    int LOW = 1;
    int HIGH = 20;
    boolean TIMER_ACTIVE = false;
    //
    //
    int result_a = 0;
    int result_b = 0;
    int flag = 0;
    boolean calc_plus;
    int TOTAL = 0;
    int CORRECT = 0;
    int WRONG = 0;
    //
    //    
    long START_CALC;
    long MAX_MS = 10000;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        TOTAL++;
        jLabel4_total.setText("" + TOTAL);
        //
        if (TIMER_ACTIVE) {
            START_CALC = System.currentTimeMillis();
            Thread x = new Thread(new Timer());
            x.start();
        }
        //
        if (flag % 2 == 0) {
            calc_plus_a();
            calc_plus = true;
        } else {
            calc_minus_a();
            calc_plus = false;
        }
        //
        flag++;
        //
        jButton1.setEnabled(false);
        //
    }//GEN-LAST:event_jButton1ActionPerformed

    class Timer implements Runnable {

        private boolean run = true;

        @Override
        public void run() {
            while (run) {
                wait_();
                //
                long diff = System.currentTimeMillis() - START_CALC;
                //
                if (diff > MAX_MS) {
                    System.out.println("TIME IS UP");
                    run = false;
                } else {
                    jLabel4_count_down.setText("" + diff);
                }
            }

        }

        private synchronized void wait_() {
            try {
                wait(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MathGame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void calc_plus_a() {
        Random r = new Random();
        result_a = r.nextInt(HIGH - LOW) + LOW;
        result_b = r.nextInt(HIGH - LOW) + LOW;
        jTextArea1.setText(result_a + " + " + result_b);
    }

    private void calc_minus_a() {
        //
        Random r = new Random();
        //
        result_a = r.nextInt(HIGH - LOW);
        result_b = r.nextInt(HIGH - LOW);
        //
        if (result_a > result_b) {
            jTextArea1.setText(result_a + " - " + result_b);
        } else {
            jTextArea1.setText(result_b + " - " + result_a);
        }
        //
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (calc_plus) {
            check_plus_a();
        } else {
            check_minus_a();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void check_plus_a() {
        //
        String val = jTextField1.getText();
        //
        if(val == null || val.isEmpty()){
            return;
        }
        //
        int resultat = Integer.parseInt(val);
        //
        if (resultat == (result_a + result_b)) {
            correctAnswer();
        } else {
            wrongAnswer();
        }
    }

    private void check_minus_a() {
        //
        int resultat = Integer.parseInt(jTextField1.getText());
        //
        if (result_a > result_b) {
            if (resultat == (result_a - result_b)) {
                correctAnswer();
            } else {
                wrongAnswer();
            }
        } else {
            if (resultat == (result_b - result_a)) {
                correctAnswer();
            } else {
                wrongAnswer();
            }
        }

    }

    private void wrongAnswer() {
        JOptionPane.showMessageDialog(null, "Fel");
        WRONG++;
        jLabel4_ammount_wrong.setText("" + WRONG);
    }

    private void correctAnswer() {
        resetResult();
        jButton1ActionPerformed(null);
        CORRECT++;
        jLabel3_ammount_correct.setText("" + CORRECT);
    }

    private void resetResult() {
        jTextField1.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_ammount_correct;
    private javax.swing.JLabel jLabel4_ammount_wrong;
    private javax.swing.JLabel jLabel4_count_down;
    private javax.swing.JLabel jLabel4_total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
